### ISSUE TITLE
how to use your code? Some problems

### ISSUE THREAD

**Issue by cgllv** [cashiwamochi/RealEstate10K_Downloader#7]
1. I use generate_dataset.py for download video, I find a small problem that in your code "if videoname_candinate.split('.')[-2] == '/current_' + mode" should change like "if videoname_candinate.split('.')[-2] == '/current_' + mode or videoname_candinate.split('.')[-2] == '\\current_' + mode:" for the reason that window file path splitter is "\\";
2. I find youtube video download failure rate pretty high,  has any method  to improve it? 
3. I also tried your visualizer.py, it' will show a  three-dimensional coordinate axis and two of planes have much side-by-side arrows, what's the meanings of it? would you give me introduction? 
Thanks a lot!

**Comment by cashiwamochi** [comment]
Thanks for your comment. 

1. I'm afraid to say that actually I don't support windows. Maybe in the future, I use pathlib module to support windows.

2. Sorry. I have no method. The problem comes from others.

3. visualizer.py shows us poses of cameras in a video, for camera at each timestamp has each three-dimensional cartesian coordinates. Maybe I don't understand what you ask(What is " two of planes have much side-by-side arrows" ?). If I don't, can you explain more or share image with your problem ?

**Comment by cgllv** [comment]
![Capture20200731130422](https://user-images.githubusercontent.com/23209160/89001973-7306c000-d32e-11ea-889e-3e6baf808e70.png)
just like this. does it right?

**Comment by cashiwamochi** [comment]
Thanks.

visualizer.py works well. As I commented, those three-dimensional cartesian coordinates show coordinate of cameras at each time in video. Only one coordinate is large because it is the first camera's coordinate in video.
When you try another data, maybe it's easy to understand what this script does.
